### ISSUE TITLE
Cannot compile without redix optional dependency.

### ISSUE THREAD

**Issue by mbramson** [tompave/fun_with_flags#58]
On Elixir 1.9.1, Erlang 21, when I try to get the project working with only the
```
{:fun_with_flags, "~> 1.4.1"},
```
line to `mix.exs` and then add the following configuration to a brand new phoenix project:

```
config :fun_with_flags, :cache_bust_notifications,
  enabled: true,
  adapter: FunWithFlags.Notifications.PhoenixPubSub,
  client: Flaggy.PubSub

config :fun_with_flags, :persistence,
  adapter: FunWithFlags.Store.Persistent.Ecto,
  repo: Flaggy.Repo
```
(`Flaggy` is the name of the phoenix app)
(I'm trying to avoid redis entirely)

I get the following compile error:
```
code/elixir/flaggy mix phx.server
Compiling 13 files (.ex)
Generated flaggy app
[error] FunWithFlags: It looks like you're trying to use FunWithFlags.Store.Persistent.Redis to persist flags, but you haven't added its optional dependency to the Mixfile of your project.
[info] Application fun_with_flags exited: exited in: FunWithFlags.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function FunWithFlags.Store.Persistent.Redis.worker_spec/0 is undefined (module FunWithFlags.Store.Persistent.Redis is not available)
            FunWithFlags.Store.Persistent.Redis.worker_spec()
            (fun_with_flags) lib/fun_with_flags/application.ex:28: FunWithFlags.Application.persistence_spec/0
            (fun_with_flags) lib/fun_with_flags/application.ex:17: FunWithFlags.Application.children/0
            (fun_with_flags) lib/fun_with_flags/application.ex:10: FunWithFlags.Application.start/2
            (kernel) application_master.erl:277: :application_master.start_it_old/4
** (Mix) Could not start application fun_with_flags: exited in: FunWithFlags.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function FunWithFlags.Store.Persistent.Redis.worker_spec/0 is undefined (module FunWithFlags.Store.Persistent.Redis is not available)
            FunWithFlags.Store.Persistent.Redis.worker_spec()
            (fun_with_flags) lib/fun_with_flags/application.ex:28: FunWithFlags.Application.persistence_spec/0
            (fun_with_flags) lib/fun_with_flags/application.ex:17: FunWithFlags.Application.children/0
            (fun_with_flags) lib/fun_with_flags/application.ex:10: FunWithFlags.Application.start/2
            (kernel) application_master.erl:277: :application_master.start_it_old/4
```
When I add `redix` to mix.exs everything works normally. It's not terrible to add the redix library, but I would like to not, as I'm not actually using it for anything.

**Comment by tompave** [comment]
Hello! Thank you for using the library and for reporting the issue.

Question: have you ever compiled the app with FWF configured to use Redis? Does the problem run away if you run this and re-try?

```shell
rm -r _build/dev/lib/fun_with_flags
rm -r _build/dev/lib/YOUR_APP_NAME
```

**Comment by mbramson** [comment]
So I tried to duplicate this again on another new phoenix project (and my original one) and didn't have any luck. ¯\_(ツ)_/¯.

Thanks for the quick response though! Closing this out.

**Comment by blakedietz** [comment]
Ugh, I just blew 30 minutes on this. The fix is definitely https://github.com/tompave/fun_with_flags/issues/58#issuecomment-564347583.
