### ISSUE TITLE
config is not applied

### ISSUE THREAD

**Issue by eteubert** [tompave/fun_with_flags#81]
Hi,

I'm setting this up in a Phoenix application. Like this:

```elixir
config :fun_with_flags, :cache,
  enabled: true,
  ttl: 900

config :fun_with_flags, :persistence,
  adapter: FunWithFlags.Store.Persistent.Ecto,
  repo: Plus.Repo,
  ecto_table_name: "fun_with_flags_toggles"

config :fun_with_flags, :cache_bust_notifications,
  enabled: true,
  adapter: FunWithFlags.Notifications.PhoenixPubSub,
  client: Plus.PubSub
```

Migration is setup, ran and I checked that the table is there.
However when I use the API, the error looks like the repo is not configured:

```elixir
iex ▶ FunWithFlags.enabled?(:my_feat)

▶▶▶
** (RuntimeError) The NullEctoRepo doesn't implement this. You must configure a proper repo to persist flags with Ecto.
    (fun_with_flags 1.5.1) lib/fun_with_flags/store/persistent/ecto/null_repo.ex:9: FunWithFlags.NullEctoRepo.all/1
    (fun_with_flags 1.5.1) lib/fun_with_flags/store/persistent/ecto.ex:32: FunWithFlags.Store.Persistent.Ecto.get/1
    (fun_with_flags 1.5.1) lib/fun_with_flags/store.ex:15: FunWithFlags.Store.lookup/1
    (fun_with_flags 1.5.1) lib/fun_with_flags.ex:77: FunWithFlags.enabled?/2
```

Checking the config in the same iex session:

```elixir
iex|2 ▶ Application.get_env(:fun_with_flags, :persistence)
[
  adapter: FunWithFlags.Store.Persistent.Ecto,
  repo: Plus.Repo,
  ecto_table_name: "fun_with_flags_toggles"
]
```

What am I missing?

**Comment by tompave** [comment]
Have you tried this? https://github.com/tompave/fun_with_flags#configuration-changes-have-no-effect-in-mix_envdev

**Comment by eteubert** [comment]
Ah, that's it 👍
